# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ListDemo

  target 'ListDemoTests' do
    inherit! :search_paths
      pod 'SDWebImage', '~> 5.0'
  end

end
